os: osx
language: objective-c
sudo: false
name: TravisCIBot

env:
  global:
    # $THEOS is absolutely needed for theos to even be found
    #- THEOS=~/theos

before_install:
  # update homebrew and install dependencies
  #- brew update

  - brew install dpkg
  - brew install md5sha1sum
  
  # install theos
 # - git clone --recursive git://github.com/theos/theos.git ~/theos

script:
  #- cd repo_layout
  - chmod +x ./repo/dpkg-scanpackages
  - ./repo/dpkg-scanpackages -m debs ./repo/debs  > ./repo/Packages
  - bzip2 -c9 ./repo/Packages > ./repo/Packages.bz2

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: master
  on:
    branch: deploy
